### ISSUE TITLE
[Feature Request] Automate Weakness use leading to Experience gain

### ISSUE THREAD

**Issue by CharlesRampant** [aMediocreDad/litm#23]
Heya, a simple request here, it would be nice to have it that when a Weakness tag is selected on a roll then the sheet automatically adds a pip to the Experience tracker.

**Comment by metamancer** [comment]
This automation would need to be optional control by GM as there are alternative rules for example, which allow increase exp gain on weakness invoked once per session, rather than each time. Forced automation of this would take away the flexibility of the systems design.

**Comment by aMediocreDad** [comment]
Could have a button that you can click... perhaps?
