### ISSUE TITLE
Challenge Actor (v3) Tag & Status input + delelting consequences

### ISSUE THREAD

**Issue by digitalsychosis** [aMediocreDad/litm#29]
(1) TAG & STATUSES has a text field which can be written into, but doesn't seem to save the text.

(2) I didn't see a way to delete consequences

**Comment by aMediocreDad** [comment]
1: It should save the text, I just didn’t tell you how to format tags. Like threats & consequences you write tags like `[tag]` and statuses like `[status 4]` or `[status-4]`.

This also works in journal entries and maybe I’ll make it work like that in the descriptions as well. (It works like that in the special features thing too).

2. Right click to delete.

**Comment by aMediocreDad** [comment]
Leaving this open until it is documented.
