### ISSUE TITLE
[Feature Request]Player-Focused Challenge Window/Optimized Story Tag Window

### ISSUE THREAD

**Issue by 0rac1e404** [aMediocreDad/litm#78]
The existing story window (even when scaled down as much as possible) is difficult to accommodate the simultaneous presentation of 5-6 actors; Is it possible to:

1. Open a window from the challenge that presents images, tags, and statuses to the player

or

2. While in the story tag window, display the tags and statuses owned when hovering over an actor, or provide a button to collapse/expand actor tags

**Comment by aMediocreDad** [comment]
If I understand you correctly the issue is that with many actors and many tags on each actor it gets crowded?

**Comment by 0rac1e404** [comment]
> If I understand you correctly the issue is that with many actors and many tags on each actor it gets crowded?

Kinda？Is there a way to split the tag window by actor or am I missing something?

**Comment by aMediocreDad** [comment]
I saw at least one issue. The window overflows so that's what I fixed here. The tag window cannot be split by actor. Characters have their tags and statuses visible on their sheet, the challenges do not, but I might add that later on.

**Comment by 0rac1e404** [comment]
Testing it,thank you for your hardworking.
I notice that there is a maximum length when lengthen the window,which would make reducing the scale kind of meaningless,for I still have to scrolling to see all the tags.Is this by design?

**Comment by aMediocreDad** [comment]
> I notice that there is a maximum length when lengthen the window,which would make reducing the scale kind of meaningless,for I still have to scrolling to see all the tags.Is this by design?

The maximum height on the window is likely a foundry default. I'll see if unsetting the maximum height does anything weird.
