### ISSUE TITLE
Add tooltip to hint at right-click to decrease experience/decay

### ISSUE THREAD

**Issue by metamancer** [aMediocreDad/litm#9]
**Steps to Reproduce:**
1. Open a themebook
2. Click all three buttons for Experience/Decay
3. Observe you cannot remove the marked experience or decay

[Screen Recording](https://drive.google.com/file/d/1Cyh3TLqyxcokglnfNaW47XBk7oYZS0On/view?usp=sharing)

**Expected Behavior:**
Clicking the buttons on Experience and Decay can be changed as needed.

**Comment by Cussa** [comment]
Can you try the right click?

**Comment by metamancer** [comment]
@Cussa - yes, right-click does allow for deactivation

**Comment by aMediocreDad** [comment]
I'll add a tooltip clue on this.
